### ISSUE TITLE
Typo causes paresing error with json

### ISSUE THREAD

**Issue by melbadry9** [projectdiscovery/public-bugbounty-programs#109]
https://github.com/projectdiscovery/public-bugbounty-programs/blob/a0915f83994b4150a0279ec98fb8828fca853851/chaos-bugbounty-list.json#L4183

- This should be altered to `domains`

**Comment by bauthard** [comment]
This is done at @melardev https://github.com/projectdiscovery/public-bugbounty-programs/commit/08564d5f9e974a5e40a664717bf14f6cfb44cfcf, thank you.
