### ISSUE TITLE
Request for new tab feature

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/public-bugbounty-programs#148]
Hi Team

Can we have a feature tab like swag 

Just like we have rewards , no rewards 
![image](https://user-images.githubusercontent.com/24750220/106242703-1b3e0880-622e-11eb-8203-4fad198f0d9b.png)

**Comment by bauthard** [comment]
@DhiyaneshGeek we can easily add this feature, but the real question is we need to fill this data in all programs and we don't have source data for the existing programs in the context of swag, do you have or suggest anything from where we can automatically fetch and update this data?

**Comment by DhiyaneshGeek** [comment]
@bauthard give me a day time , i will collect  at-least 50 programs which offers swag

**Comment by DhiyaneshGeek** [comment]
@bauthard Yup i have added those swag domains

**Comment by DhiyaneshGeek** [comment]
@ehsandeep this issue is fixed we can close this thread

**Comment by ehsandeep** [comment]
Thank you @DhiyaneshGeek for taking initiative for this, this is now live on the [chaos website](https://chaos.projectdiscovery.io/#/).
