### ISSUE TITLE
Adding JSON validator check on PR and push request

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/public-bugbounty-programs#18]
Like we have in [nuclei-templates](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/workflows/syntax-checking.yml) for YAML.

**Comment by mzfr** [comment]
Not sure if it's possible via jsonlint but we can use something like [validate-json-action](https://github.com/OrRosenblatt/validate-json-action).

For this to work we'd just have to write a schema against which the newly submitted json would be checked.

If you'd be okay with it then I'd be willing to make the PR for this.

**Comment by bauthard** [comment]
Hey @mzfr, thanks a lot for offering help on this, please go on! 

we need to ensure the syntax is valid which will be checked on each PR / PUSH.
