### ISSUE TITLE
Improve the JSON sorting workflow

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/public-bugbounty-programs#348]
The sorting itself should be case insensitive and as easy as:
```js
fetch('https://cdn.jsdelivr.net/gh/projectdiscovery/public-bugbounty-programs@master/chaos-bugbounty-list.json')
.then(response => response.json())
.then(data => {
    data.programs.sort(function(a,b) { return a.name.toLowerCase() > b.name.toLowerCase() })
    return data
})
.then(data => console.log(JSON.stringify(data)))
```

![image](https://user-images.githubusercontent.com/13679401/181787146-1c97723a-663b-4c3d-8400-c222476ddfd7.png)

Current workflow: https://github.com/projectdiscovery/public-bugbounty-programs/blob/master/.github/workflows/json-sorting.yml

**Comment by Ice3man543** [comment]
https://stackoverflow.com/questions/72277908/how-to-sort-case-insensitive-using-jq - for case insensitive sorting by using sort_by
