### ISSUE TITLE
Ability to exclude out of scope subdomain

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/public-bugbounty-programs#439]
Hi,

A lot of program has out of scope subdomain. Testing on these subdomains are prohibited.

As you can see below, these programs on Chaos have millions of enumerated subdomain where 99% are out of scope : 

<img width="1267" alt="Capture d’écran 2023-01-01 à 12 46 25" src="https://user-images.githubusercontent.com/99909324/210169617-22a9fcb5-ef7d-4c70-8dee-d32c8018c223.png">

**Comment by ehsandeep** [comment]
@akincibor see https://github.com/projectdiscovery/public-bugbounty-programs/issues/77#issuecomment-660535707
