### ISSUE TITLE
Program doesn't show up on https://chaos.projectdiscovery.io/#/

### ISSUE THREAD

**Issue by oivrip** [projectdiscovery/public-bugbounty-programs#475]
Hi,

I opened a PR as you can see from here: https://github.com/projectdiscovery/public-bugbounty-programs/pull/450 and it is merged. Although I saw the program on the site for the first few days, I couldn't see it afterwards. Is there a bug here?

Also, this problem is occurred more than one program as I can see. I search for "Agicap", "Sendcloud" etc. and can't see any result on https://chaos.projectdiscovery.io/

**Comment by h0wardR** [comment]
Hi there. 
Same problem, [PR](https://github.com/projectdiscovery/public-bugbounty-programs/pull/493) but the program does not appear on the site.
