### ISSUE TITLE
Bug in `ValidateFQDN` function

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/public-bugbounty-programs#532]
from https://github.com/projectdiscovery/public-bugbounty-programs/blob/main/pkg/dns/dns.go#L27-L36

```go
func ValidateFQDN(value string) bool {
	// check if domain can can be parsed
	tld, err := publicsuffix.EffectiveTLDPlusOne(value)
	if err != nil {
		return false
	}

	// check if top level domain is equal to original and it's a valid domain name
	return tld == value && govalidator.IsDNSName(tld)
}
``` 

flagging `ngrok.io` as invalid domain - https://github.com/projectdiscovery/public-bugbounty-programs/actions/runs/5364609119/jobs/9732904993

**Comment by MattSilvaa** [comment]
Hey! I can take this on

**Comment by MattSilvaa** [comment]
So it seems like the reason this is occurring is because `ngrok.io` is in the [PSL](https://publicsuffix.org/list/public_suffix_list.dat). Do you want to change the fqdn logic to not consider the PSL when validating?
