### ISSUE TITLE
Question- Defining program scope? 

### ISSUE THREAD

**Issue by The-Rabbit-of-Caerbannog** [projectdiscovery/public-bugbounty-programs#77]
It is getting more common for programs to have an *.sub.example.com scope. Would these be valuable/relevant to add to this list if they don't have a *.example.com scope, too? 

Also, many programs will list a wildcard subdomain scope (*.example.com) but then list specific subdomains as out of scope. Is there a way to define these? They can change often so it may be best to leave it as is, and for researchers to verify the current program scope before testing (which hopefully they already do).

**Comment by bauthard** [comment]
Hi @The-Rabbit-of-Caerbannog, 

This list aims to maintain base information of the bug bounty programs including program URL and base domains and not scope, to keep all the data uniform, we are following the format as defined in the readme. 

let me know if you still have any questions. 

> They can change often so it may be best to leave it as is, and for researchers to verify the current program scope before testing (which hopefully they already do).

Yes, you are right.
