### ISSUE TITLE
Swisscom Domains not added 

### ISSUE THREAD

**Issue by ved009** [projectdiscovery/public-bugbounty-programs#896]
Hello, 

The swisscom Domains are not added which resulted in zero responses in chaos data. Shall I do a pull request to add the same?

**Comment by GeorginaReeder** [comment]
Hi @ved009 ! Yes please, if you can go ahead and create a pull request, we'll be able to take a closer look from there.

**Comment by ehsandeep** [comment]
@ved009 it was removed from team member, for context - https://github.com/projectdiscovery/public-bugbounty-programs/pull/541
